coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5
        base: auto
        flags:
          - unit
        paths:
          - "src"
       # advanced settings
        branches:
          - main
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false
